// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.GetMarketDepthResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api.MarketDepthItem');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.GetMarketDepthResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.GetMarketDepthResponse.repeatedFields_, null);
};
goog.inherits(proto.api.GetMarketDepthResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.GetMarketDepthResponse.displayName = 'proto.api.GetMarketDepthResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.GetMarketDepthResponse.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.GetMarketDepthResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.GetMarketDepthResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.GetMarketDepthResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.GetMarketDepthResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    market: jspb.Message.getFieldWithDefault(msg, 1, ""),
    marketaddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    bidsList: jspb.Message.toObjectList(msg.getBidsList(),
    proto.api.MarketDepthItem.toObject, includeInstance),
    asksList: jspb.Message.toObjectList(msg.getAsksList(),
    proto.api.MarketDepthItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.GetMarketDepthResponse}
 */
proto.api.GetMarketDepthResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.GetMarketDepthResponse;
  return proto.api.GetMarketDepthResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.GetMarketDepthResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.GetMarketDepthResponse}
 */
proto.api.GetMarketDepthResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketaddress(value);
      break;
    case 3:
      var value = new proto.api.MarketDepthItem;
      reader.readMessage(value,proto.api.MarketDepthItem.deserializeBinaryFromReader);
      msg.addBids(value);
      break;
    case 4:
      var value = new proto.api.MarketDepthItem;
      reader.readMessage(value,proto.api.MarketDepthItem.deserializeBinaryFromReader);
      msg.addAsks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.GetMarketDepthResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.GetMarketDepthResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.GetMarketDepthResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.GetMarketDepthResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMarketaddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api.MarketDepthItem.serializeBinaryToWriter
    );
  }
  f = message.getAsksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.api.MarketDepthItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string market = 1;
 * @return {string}
 */
proto.api.GetMarketDepthResponse.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetMarketDepthResponse} returns this
 */
proto.api.GetMarketDepthResponse.prototype.setMarket = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string marketAddress = 2;
 * @return {string}
 */
proto.api.GetMarketDepthResponse.prototype.getMarketaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetMarketDepthResponse} returns this
 */
proto.api.GetMarketDepthResponse.prototype.setMarketaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated MarketDepthItem bids = 3;
 * @return {!Array<!proto.api.MarketDepthItem>}
 */
proto.api.GetMarketDepthResponse.prototype.getBidsList = function() {
  return /** @type{!Array<!proto.api.MarketDepthItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.MarketDepthItem, 3));
};


/**
 * @param {!Array<!proto.api.MarketDepthItem>} value
 * @return {!proto.api.GetMarketDepthResponse} returns this
*/
proto.api.GetMarketDepthResponse.prototype.setBidsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api.MarketDepthItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.MarketDepthItem}
 */
proto.api.GetMarketDepthResponse.prototype.addBids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api.MarketDepthItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.GetMarketDepthResponse} returns this
 */
proto.api.GetMarketDepthResponse.prototype.clearBidsList = function() {
  return this.setBidsList([]);
};


/**
 * repeated MarketDepthItem asks = 4;
 * @return {!Array<!proto.api.MarketDepthItem>}
 */
proto.api.GetMarketDepthResponse.prototype.getAsksList = function() {
  return /** @type{!Array<!proto.api.MarketDepthItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.MarketDepthItem, 4));
};


/**
 * @param {!Array<!proto.api.MarketDepthItem>} value
 * @return {!proto.api.GetMarketDepthResponse} returns this
*/
proto.api.GetMarketDepthResponse.prototype.setAsksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.api.MarketDepthItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.MarketDepthItem}
 */
proto.api.GetMarketDepthResponse.prototype.addAsks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.api.MarketDepthItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.GetMarketDepthResponse} returns this
 */
proto.api.GetMarketDepthResponse.prototype.clearAsksList = function() {
  return this.setAsksList([]);
};


