// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.GetQuotesResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api.ProjectQuote');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.GetQuotesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.GetQuotesResponse.repeatedFields_, null);
};
goog.inherits(proto.api.GetQuotesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.GetQuotesResponse.displayName = 'proto.api.GetQuotesResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.GetQuotesResponse.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.GetQuotesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.GetQuotesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.GetQuotesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.GetQuotesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    intoken: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intokenaddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    outtoken: jspb.Message.getFieldWithDefault(msg, 3, ""),
    outtokenaddress: jspb.Message.getFieldWithDefault(msg, 4, ""),
    inamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    quotesList: jspb.Message.toObjectList(msg.getQuotesList(),
    proto.api.ProjectQuote.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.GetQuotesResponse}
 */
proto.api.GetQuotesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.GetQuotesResponse;
  return proto.api.GetQuotesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.GetQuotesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.GetQuotesResponse}
 */
proto.api.GetQuotesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntoken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntokenaddress(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOuttoken(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setOuttokenaddress(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInamount(value);
      break;
    case 6:
      var value = new proto.api.ProjectQuote;
      reader.readMessage(value,proto.api.ProjectQuote.deserializeBinaryFromReader);
      msg.addQuotes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.GetQuotesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.GetQuotesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.GetQuotesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.GetQuotesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntokenaddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOuttoken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOuttokenaddress();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getInamount();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getQuotesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.api.ProjectQuote.serializeBinaryToWriter
    );
  }
};


/**
 * optional string inToken = 1;
 * @return {string}
 */
proto.api.GetQuotesResponse.prototype.getIntoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetQuotesResponse} returns this
 */
proto.api.GetQuotesResponse.prototype.setIntoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string inTokenAddress = 2;
 * @return {string}
 */
proto.api.GetQuotesResponse.prototype.getIntokenaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetQuotesResponse} returns this
 */
proto.api.GetQuotesResponse.prototype.setIntokenaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string outToken = 3;
 * @return {string}
 */
proto.api.GetQuotesResponse.prototype.getOuttoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetQuotesResponse} returns this
 */
proto.api.GetQuotesResponse.prototype.setOuttoken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string outTokenAddress = 4;
 * @return {string}
 */
proto.api.GetQuotesResponse.prototype.getOuttokenaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetQuotesResponse} returns this
 */
proto.api.GetQuotesResponse.prototype.setOuttokenaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional double inAmount = 5;
 * @return {number}
 */
proto.api.GetQuotesResponse.prototype.getInamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.GetQuotesResponse} returns this
 */
proto.api.GetQuotesResponse.prototype.setInamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * repeated ProjectQuote quotes = 6;
 * @return {!Array<!proto.api.ProjectQuote>}
 */
proto.api.GetQuotesResponse.prototype.getQuotesList = function() {
  return /** @type{!Array<!proto.api.ProjectQuote>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.ProjectQuote, 6));
};


/**
 * @param {!Array<!proto.api.ProjectQuote>} value
 * @return {!proto.api.GetQuotesResponse} returns this
*/
proto.api.GetQuotesResponse.prototype.setQuotesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.api.ProjectQuote=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.ProjectQuote}
 */
proto.api.GetQuotesResponse.prototype.addQuotes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.api.ProjectQuote, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.GetQuotesResponse} returns this
 */
proto.api.GetQuotesResponse.prototype.clearQuotesList = function() {
  return this.setQuotesList([]);
};


