// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.GetSwapsStreamUpdate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.api.Project');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.GetSwapsStreamUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.GetSwapsStreamUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.GetSwapsStreamUpdate.displayName = 'proto.api.GetSwapsStreamUpdate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.GetSwapsStreamUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.api.GetSwapsStreamUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.GetSwapsStreamUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.GetSwapsStreamUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    project: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pooladdress: jspb.Message.getFieldWithDefault(msg, 3, ""),
    intoken: jspb.Message.getFieldWithDefault(msg, 4, ""),
    intokenaddress: jspb.Message.getFieldWithDefault(msg, 5, ""),
    outtoken: jspb.Message.getFieldWithDefault(msg, 6, ""),
    outtokenaddress: jspb.Message.getFieldWithDefault(msg, 7, ""),
    inamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    outamountmin: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    sourceaccount: jspb.Message.getFieldWithDefault(msg, 10, ""),
    destinationaccount: jspb.Message.getFieldWithDefault(msg, 11, ""),
    owneraccount: jspb.Message.getFieldWithDefault(msg, 12, ""),
    signature: jspb.Message.getFieldWithDefault(msg, 13, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.GetSwapsStreamUpdate}
 */
proto.api.GetSwapsStreamUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.GetSwapsStreamUpdate;
  return proto.api.GetSwapsStreamUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.GetSwapsStreamUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.GetSwapsStreamUpdate}
 */
proto.api.GetSwapsStreamUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {!proto.api.Project} */ (reader.readEnum());
      msg.setProject(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPooladdress(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntoken(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntokenaddress(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOuttoken(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setOuttokenaddress(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInamount(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOutamountmin(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceaccount(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestinationaccount(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwneraccount(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.GetSwapsStreamUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.GetSwapsStreamUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.GetSwapsStreamUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.GetSwapsStreamUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getProject();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPooladdress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIntoken();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIntokenaddress();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getOuttoken();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getOuttokenaddress();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getInamount();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getOutamountmin();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getSourceaccount();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getDestinationaccount();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getOwneraccount();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.api.GetSwapsStreamUpdate.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional Project project = 2;
 * @return {!proto.api.Project}
 */
proto.api.GetSwapsStreamUpdate.prototype.getProject = function() {
  return /** @type {!proto.api.Project} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.api.Project} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setProject = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string poolAddress = 3;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getPooladdress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setPooladdress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string inToken = 4;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getIntoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setIntoken = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string inTokenAddress = 5;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getIntokenaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setIntokenaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string outToken = 6;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getOuttoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setOuttoken = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string outTokenAddress = 7;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getOuttokenaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setOuttokenaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional double inAmount = 8;
 * @return {number}
 */
proto.api.GetSwapsStreamUpdate.prototype.getInamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setInamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double outAmountMin = 9;
 * @return {number}
 */
proto.api.GetSwapsStreamUpdate.prototype.getOutamountmin = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setOutamountmin = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional string sourceAccount = 10;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getSourceaccount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setSourceaccount = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string destinationAccount = 11;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getDestinationaccount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setDestinationaccount = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string ownerAccount = 12;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getOwneraccount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setOwneraccount = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string signature = 13;
 * @return {string}
 */
proto.api.GetSwapsStreamUpdate.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.GetSwapsStreamUpdate} returns this
 */
proto.api.GetSwapsStreamUpdate.prototype.setSignature = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


