// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.PostCancelByClientOrderIDRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.api.Project');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.PostCancelByClientOrderIDRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.PostCancelByClientOrderIDRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.PostCancelByClientOrderIDRequest.displayName = 'proto.api.PostCancelByClientOrderIDRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.PostCancelByClientOrderIDRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.PostCancelByClientOrderIDRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.PostCancelByClientOrderIDRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientorderid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    marketaddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    owneraddress: jspb.Message.getFieldWithDefault(msg, 3, ""),
    openordersaddress: jspb.Message.getFieldWithDefault(msg, 4, ""),
    project: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.PostCancelByClientOrderIDRequest}
 */
proto.api.PostCancelByClientOrderIDRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.PostCancelByClientOrderIDRequest;
  return proto.api.PostCancelByClientOrderIDRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.PostCancelByClientOrderIDRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.PostCancelByClientOrderIDRequest}
 */
proto.api.PostCancelByClientOrderIDRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setClientorderid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarketaddress(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwneraddress(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setOpenordersaddress(value);
      break;
    case 5:
      var value = /** @type {!proto.api.Project} */ (reader.readEnum());
      msg.setProject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.PostCancelByClientOrderIDRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.PostCancelByClientOrderIDRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.PostCancelByClientOrderIDRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientorderid();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getMarketaddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOwneraddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOpenordersaddress();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getProject();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional uint64 clientOrderID = 1;
 * @return {number}
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.getClientorderid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.PostCancelByClientOrderIDRequest} returns this
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.setClientorderid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string marketAddress = 2;
 * @return {string}
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.getMarketaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.PostCancelByClientOrderIDRequest} returns this
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.setMarketaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ownerAddress = 3;
 * @return {string}
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.getOwneraddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.PostCancelByClientOrderIDRequest} returns this
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.setOwneraddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string openOrdersAddress = 4;
 * @return {string}
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.getOpenordersaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.PostCancelByClientOrderIDRequest} returns this
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.setOpenordersaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Project project = 5;
 * @return {!proto.api.Project}
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.getProject = function() {
  return /** @type {!proto.api.Project} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.api.Project} value
 * @return {!proto.api.PostCancelByClientOrderIDRequest} returns this
 */
proto.api.PostCancelByClientOrderIDRequest.prototype.setProject = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


