// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.PostOrderRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.api.OrderType');
goog.forwardDeclare('proto.api.Project');
goog.forwardDeclare('proto.api.Side');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.PostOrderRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.PostOrderRequest.repeatedFields_, null);
};
goog.inherits(proto.api.PostOrderRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.PostOrderRequest.displayName = 'proto.api.PostOrderRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.PostOrderRequest.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.PostOrderRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.PostOrderRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.PostOrderRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.PostOrderRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    owneraddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    payeraddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    market: jspb.Message.getFieldWithDefault(msg, 3, ""),
    side: jspb.Message.getFieldWithDefault(msg, 4, 0),
    typeList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    openordersaddress: jspb.Message.getFieldWithDefault(msg, 8, ""),
    clientorderid: jspb.Message.getFieldWithDefault(msg, 9, 0),
    project: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.PostOrderRequest}
 */
proto.api.PostOrderRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.PostOrderRequest;
  return proto.api.PostOrderRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.PostOrderRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.PostOrderRequest}
 */
proto.api.PostOrderRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwneraddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayeraddress(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarket(value);
      break;
    case 4:
      var value = /** @type {!proto.api.Side} */ (reader.readEnum());
      msg.setSide(value);
      break;
    case 5:
      var values = /** @type {!Array<!proto.api.OrderType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addType(values[i]);
      }
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setOpenordersaddress(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setClientorderid(value);
      break;
    case 10:
      var value = /** @type {!proto.api.Project} */ (reader.readEnum());
      msg.setProject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.PostOrderRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.PostOrderRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.PostOrderRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.PostOrderRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOwneraddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPayeraddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMarket();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSide();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTypeList();
  if (f.length > 0) {
    writer.writePackedEnum(
      5,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getOpenordersaddress();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getClientorderid();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getProject();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
};


/**
 * optional string ownerAddress = 1;
 * @return {string}
 */
proto.api.PostOrderRequest.prototype.getOwneraddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setOwneraddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string payerAddress = 2;
 * @return {string}
 */
proto.api.PostOrderRequest.prototype.getPayeraddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setPayeraddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string market = 3;
 * @return {string}
 */
proto.api.PostOrderRequest.prototype.getMarket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setMarket = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Side side = 4;
 * @return {!proto.api.Side}
 */
proto.api.PostOrderRequest.prototype.getSide = function() {
  return /** @type {!proto.api.Side} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.api.Side} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setSide = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * repeated OrderType type = 5;
 * @return {!Array<!proto.api.OrderType>}
 */
proto.api.PostOrderRequest.prototype.getTypeList = function() {
  return /** @type {!Array<!proto.api.OrderType>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<!proto.api.OrderType>} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setTypeList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!proto.api.OrderType} value
 * @param {number=} opt_index
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.addType = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.clearTypeList = function() {
  return this.setTypeList([]);
};


/**
 * optional double amount = 6;
 * @return {number}
 */
proto.api.PostOrderRequest.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double price = 7;
 * @return {number}
 */
proto.api.PostOrderRequest.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional string openOrdersAddress = 8;
 * @return {string}
 */
proto.api.PostOrderRequest.prototype.getOpenordersaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setOpenordersaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional uint64 clientOrderID = 9;
 * @return {number}
 */
proto.api.PostOrderRequest.prototype.getClientorderid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setClientorderid = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional Project project = 10;
 * @return {!proto.api.Project}
 */
proto.api.PostOrderRequest.prototype.getProject = function() {
  return /** @type {!proto.api.Project} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.api.Project} value
 * @return {!proto.api.PostOrderRequest} returns this
 */
proto.api.PostOrderRequest.prototype.setProject = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


