// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.ProjectPool');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ProjectPool = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.ProjectPool, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.ProjectPool.displayName = 'proto.api.ProjectPool';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ProjectPool.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ProjectPool.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ProjectPool} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.ProjectPool.toObject = function(includeInstance, msg) {
  var f, obj = {
    pool: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pooladdress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    token1reserves: jspb.Message.getFieldWithDefault(msg, 3, 0),
    token1mintaddress: jspb.Message.getFieldWithDefault(msg, 4, ""),
    token1mintsymbol: jspb.Message.getFieldWithDefault(msg, 5, ""),
    token2reserves: jspb.Message.getFieldWithDefault(msg, 6, 0),
    token2mintaddress: jspb.Message.getFieldWithDefault(msg, 7, ""),
    token2mintsymbol: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ProjectPool}
 */
proto.api.ProjectPool.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ProjectPool;
  return proto.api.ProjectPool.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ProjectPool} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ProjectPool}
 */
proto.api.ProjectPool.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPool(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPooladdress(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setToken1reserves(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken1mintaddress(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken1mintsymbol(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setToken2reserves(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken2mintaddress(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken2mintsymbol(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ProjectPool.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.ProjectPool.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.ProjectPool} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.ProjectPool.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPool();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPooladdress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getToken1reserves();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getToken1mintaddress();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getToken1mintsymbol();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getToken2reserves();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getToken2mintaddress();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getToken2mintsymbol();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string pool = 1;
 * @return {string}
 */
proto.api.ProjectPool.prototype.getPool = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setPool = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string poolAddress = 2;
 * @return {string}
 */
proto.api.ProjectPool.prototype.getPooladdress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setPooladdress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 token1Reserves = 3;
 * @return {number}
 */
proto.api.ProjectPool.prototype.getToken1reserves = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setToken1reserves = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string token1MintAddress = 4;
 * @return {string}
 */
proto.api.ProjectPool.prototype.getToken1mintaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setToken1mintaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string token1MintSymbol = 5;
 * @return {string}
 */
proto.api.ProjectPool.prototype.getToken1mintsymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setToken1mintsymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 token2Reserves = 6;
 * @return {number}
 */
proto.api.ProjectPool.prototype.getToken2reserves = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setToken2reserves = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string token2MintAddress = 7;
 * @return {string}
 */
proto.api.ProjectPool.prototype.getToken2mintaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setToken2mintaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string token2MintSymbol = 8;
 * @return {string}
 */
proto.api.ProjectPool.prototype.getToken2mintsymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.ProjectPool} returns this
 */
proto.api.ProjectPool.prototype.setToken2mintsymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


