// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.RouteTradeSwapRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api.RouteStep');

goog.forwardDeclare('proto.api.Project');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.RouteTradeSwapRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.RouteTradeSwapRequest.repeatedFields_, null);
};
goog.inherits(proto.api.RouteTradeSwapRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.RouteTradeSwapRequest.displayName = 'proto.api.RouteTradeSwapRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.RouteTradeSwapRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.RouteTradeSwapRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.RouteTradeSwapRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.RouteTradeSwapRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.RouteTradeSwapRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    project: jspb.Message.getFieldWithDefault(msg, 1, 0),
    owneraddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stepsList: jspb.Message.toObjectList(msg.getStepsList(),
    proto.api.RouteStep.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.RouteTradeSwapRequest}
 */
proto.api.RouteTradeSwapRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.RouteTradeSwapRequest;
  return proto.api.RouteTradeSwapRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.RouteTradeSwapRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.RouteTradeSwapRequest}
 */
proto.api.RouteTradeSwapRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.api.Project} */ (reader.readEnum());
      msg.setProject(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwneraddress(value);
      break;
    case 3:
      var value = new proto.api.RouteStep;
      reader.readMessage(value,proto.api.RouteStep.deserializeBinaryFromReader);
      msg.addSteps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.RouteTradeSwapRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.RouteTradeSwapRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.RouteTradeSwapRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.RouteTradeSwapRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProject();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getOwneraddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStepsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api.RouteStep.serializeBinaryToWriter
    );
  }
};


/**
 * optional Project project = 1;
 * @return {!proto.api.Project}
 */
proto.api.RouteTradeSwapRequest.prototype.getProject = function() {
  return /** @type {!proto.api.Project} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.api.Project} value
 * @return {!proto.api.RouteTradeSwapRequest} returns this
 */
proto.api.RouteTradeSwapRequest.prototype.setProject = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string ownerAddress = 2;
 * @return {string}
 */
proto.api.RouteTradeSwapRequest.prototype.getOwneraddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.RouteTradeSwapRequest} returns this
 */
proto.api.RouteTradeSwapRequest.prototype.setOwneraddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated RouteStep steps = 3;
 * @return {!Array<!proto.api.RouteStep>}
 */
proto.api.RouteTradeSwapRequest.prototype.getStepsList = function() {
  return /** @type{!Array<!proto.api.RouteStep>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.RouteStep, 3));
};


/**
 * @param {!Array<!proto.api.RouteStep>} value
 * @return {!proto.api.RouteTradeSwapRequest} returns this
*/
proto.api.RouteTradeSwapRequest.prototype.setStepsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api.RouteStep=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.RouteStep}
 */
proto.api.RouteTradeSwapRequest.prototype.addSteps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api.RouteStep, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.RouteTradeSwapRequest} returns this
 */
proto.api.RouteTradeSwapRequest.prototype.clearStepsList = function() {
  return this.setStepsList([]);
};


