// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.RouteStep');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api.StepProject');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.RouteStep = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.RouteStep, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.RouteStep.displayName = 'proto.api.RouteStep';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.RouteStep.prototype.toObject = function(opt_includeInstance) {
  return proto.api.RouteStep.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.RouteStep} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.RouteStep.toObject = function(includeInstance, msg) {
  var f, obj = {
    intoken: jspb.Message.getFieldWithDefault(msg, 1, ""),
    inamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    outtoken: jspb.Message.getFieldWithDefault(msg, 3, ""),
    outamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    outamountmin: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    project: (f = msg.getProject()) && proto.api.StepProject.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.RouteStep}
 */
proto.api.RouteStep.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.RouteStep;
  return proto.api.RouteStep.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.RouteStep} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.RouteStep}
 */
proto.api.RouteStep.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntoken(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInamount(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOuttoken(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOutamount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOutamountmin(value);
      break;
    case 6:
      var value = new proto.api.StepProject;
      reader.readMessage(value,proto.api.StepProject.deserializeBinaryFromReader);
      msg.setProject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.RouteStep.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.RouteStep.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.RouteStep} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.RouteStep.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInamount();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getOuttoken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOutamount();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getOutamountmin();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getProject();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.api.StepProject.serializeBinaryToWriter
    );
  }
};


/**
 * optional string inToken = 1;
 * @return {string}
 */
proto.api.RouteStep.prototype.getIntoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.RouteStep} returns this
 */
proto.api.RouteStep.prototype.setIntoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double inAmount = 2;
 * @return {number}
 */
proto.api.RouteStep.prototype.getInamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.RouteStep} returns this
 */
proto.api.RouteStep.prototype.setInamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string outToken = 3;
 * @return {string}
 */
proto.api.RouteStep.prototype.getOuttoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.RouteStep} returns this
 */
proto.api.RouteStep.prototype.setOuttoken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional double outAmount = 4;
 * @return {number}
 */
proto.api.RouteStep.prototype.getOutamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.RouteStep} returns this
 */
proto.api.RouteStep.prototype.setOutamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double outAmountMin = 5;
 * @return {number}
 */
proto.api.RouteStep.prototype.getOutamountmin = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api.RouteStep} returns this
 */
proto.api.RouteStep.prototype.setOutamountmin = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional StepProject project = 6;
 * @return {?proto.api.StepProject}
 */
proto.api.RouteStep.prototype.getProject = function() {
  return /** @type{?proto.api.StepProject} */ (
    jspb.Message.getWrapperField(this, proto.api.StepProject, 6));
};


/**
 * @param {?proto.api.StepProject|undefined} value
 * @return {!proto.api.RouteStep} returns this
*/
proto.api.RouteStep.prototype.setProject = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.RouteStep} returns this
 */
proto.api.RouteStep.prototype.clearProject = function() {
  return this.setProject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.RouteStep.prototype.hasProject = function() {
  return jspb.Message.getField(this, 6) != null;
};


