// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.api.UnsettledAccount');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api.UnsettledAccountToken');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.UnsettledAccount = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.UnsettledAccount, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.UnsettledAccount.displayName = 'proto.api.UnsettledAccount';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.UnsettledAccount.prototype.toObject = function(opt_includeInstance) {
  return proto.api.UnsettledAccount.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.UnsettledAccount} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.UnsettledAccount.toObject = function(includeInstance, msg) {
  var f, obj = {
    account: jspb.Message.getFieldWithDefault(msg, 1, ""),
    basetoken: (f = msg.getBasetoken()) && proto.api.UnsettledAccountToken.toObject(includeInstance, f),
    quotetoken: (f = msg.getQuotetoken()) && proto.api.UnsettledAccountToken.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.UnsettledAccount}
 */
proto.api.UnsettledAccount.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.UnsettledAccount;
  return proto.api.UnsettledAccount.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.UnsettledAccount} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.UnsettledAccount}
 */
proto.api.UnsettledAccount.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccount(value);
      break;
    case 2:
      var value = new proto.api.UnsettledAccountToken;
      reader.readMessage(value,proto.api.UnsettledAccountToken.deserializeBinaryFromReader);
      msg.setBasetoken(value);
      break;
    case 3:
      var value = new proto.api.UnsettledAccountToken;
      reader.readMessage(value,proto.api.UnsettledAccountToken.deserializeBinaryFromReader);
      msg.setQuotetoken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.UnsettledAccount.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.UnsettledAccount.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.UnsettledAccount} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.UnsettledAccount.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccount();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBasetoken();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api.UnsettledAccountToken.serializeBinaryToWriter
    );
  }
  f = message.getQuotetoken();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.api.UnsettledAccountToken.serializeBinaryToWriter
    );
  }
};


/**
 * optional string account = 1;
 * @return {string}
 */
proto.api.UnsettledAccount.prototype.getAccount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.UnsettledAccount} returns this
 */
proto.api.UnsettledAccount.prototype.setAccount = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional UnsettledAccountToken baseToken = 2;
 * @return {?proto.api.UnsettledAccountToken}
 */
proto.api.UnsettledAccount.prototype.getBasetoken = function() {
  return /** @type{?proto.api.UnsettledAccountToken} */ (
    jspb.Message.getWrapperField(this, proto.api.UnsettledAccountToken, 2));
};


/**
 * @param {?proto.api.UnsettledAccountToken|undefined} value
 * @return {!proto.api.UnsettledAccount} returns this
*/
proto.api.UnsettledAccount.prototype.setBasetoken = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.UnsettledAccount} returns this
 */
proto.api.UnsettledAccount.prototype.clearBasetoken = function() {
  return this.setBasetoken(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.UnsettledAccount.prototype.hasBasetoken = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional UnsettledAccountToken quoteToken = 3;
 * @return {?proto.api.UnsettledAccountToken}
 */
proto.api.UnsettledAccount.prototype.getQuotetoken = function() {
  return /** @type{?proto.api.UnsettledAccountToken} */ (
    jspb.Message.getWrapperField(this, proto.api.UnsettledAccountToken, 3));
};


/**
 * @param {?proto.api.UnsettledAccountToken|undefined} value
 * @return {!proto.api.UnsettledAccount} returns this
*/
proto.api.UnsettledAccount.prototype.setQuotetoken = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.UnsettledAccount} returns this
 */
proto.api.UnsettledAccount.prototype.clearQuotetoken = function() {
  return this.setQuotetoken(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.UnsettledAccount.prototype.hasQuotetoken = function() {
  return jspb.Message.getField(this, 3) != null;
};


